osx_image: xcode9
language: objective-c
before_install:
  - carthage bootstrap --platform ios
script:
    - swiftlint
    - xcodebuild test -project SampleApp.xcodeproj -scheme SampleApp -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1'
