//
// Micropost.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Return all users. */
open class Micropost: JSONEncodable {

    /** Micropost ID. */
    public var id: Int?
    /** Micropost content. */
    public var content: String?
    /** User ID of the micropost. */
    public var userId: Int?
    /** Picture info added to the micropost. */
    public var picture: Picture?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["content"] = self.content
        nillableDictionary["user_id"] = self.userId?.encodeToJSON()
        nillableDictionary["picture"] = self.picture?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
